name: Deploy Lambda

on:
  push:
    branches:
    - master
    - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21'
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: bootstrap
          run: |
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bootstrap main.go && zip deployment.zip bootstrap
        - name: deploy
          run: |
            aws lambda update-function-code --function-name=lexbot-lambda --zip-file=fileb://deployment.zip